import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import ToogleTheme from "./components/ToogleTheme";
import ThemeContextWrapper from "./context/ThemeContextWrapper";
import "./globals.css";
import { ThemeProvider } from "./hooks/useTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      // data-theme={"cupcake"}
    >
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <ThemeContextWrapper>
              <NavBar />
              <ToogleTheme />
              <main className='p-4'>{children}</main>
            </ThemeContextWrapper>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
